### ISSUE TITLE
Errors during test of ldap sync setup

### ISSUE THREAD

**Issue by Luckyvb** [Luckyvb/redmine_ldap_sync#1]
[https://github.com/thorin/redmine_ldap_sync/issues/221](url)

Test button does nothing, however then I try to enable config redmine says that my settings are invalid.

Relevant section of production log:

Processing by LdapSettingsController#test as TEXT
  Parameters: {"id"=>"1"}
  Current user: einhander (id=3)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 10.3ms)

NoMethodError (undefined method `fetch' for nil:NilClass):
  plugins/redmine_ldap_sync/app/controllers/ldap_settings_controller.rb:83:in `test'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Ldap authorization works fine, I can log in with ldap user.

ldap_settings.js must send data from form but something wrong
`  $('#commit-test')
    .bind('ajax:before', function() {
      var data = $('form[id^="edit_ldap_setting"]').serialize();
      $(this).data('params', data);
    })
    .bind('ajax:success', function(event, data) {
      $('#test-result').text(data);
    });`

by log params:
{"controller"=>"ldap_settings", "action"=>"test", "id"=>"1", "format"=>"text"}

**Comment by Luckyvb** [comment]
`  $('#commit-test')
    .bind('ajax:before', function(event, xhr, settings) {
      $(this).attr('data-params', $('input[name^="ldap_test"]').serialize())
    })
    .bind('ajax:success', function(event, data) {
      $('#test-result').text(data ?? event.detail[0]);
    })
    .bind('ajax:error', function(event, data) {
      $('#test-result').text("Error!!!");
    });
`

**Comment by Luckyvb** [comment]
[e689a2e](https://github.com/Luckyvb/redmine_ldap_sync/commit/e689a2e817f769ff0bc41f72c3366ca85e2d8fa5)
